ARG NODE_VERSION=22.3.0
ARG NGINX_VERSION=1.27-alpine
ARG PORT=9069

FROM node:${NODE_VERSION} AS builder
WORKDIR /usr/src/app
COPY ./src ./src
COPY ./package* .
COPY ./builder.config.js .
COPY ./config ./config
COPY ./tools/builder ./tools/builder
COPY ./tools/deployment ./tools/deployment
COPY ./tools/utils ./tools/utils
COPY ./public ./public
RUN npm ci && \
    npm run build:prod

FROM nginx:${NGINX_VERSION}

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/tools/deployment/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist/src /usr/share/nginx/html

EXPOSE ${PORT}

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:${PORT}/health || exit 1

CMD ["nginx", "-g", "daemon off;"]