export const chalk = {
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  blue: (s) => `\x1b[34m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  purple: (s) => `\x1b[35m${s}\x1b[0m`,
  gray: (s) => `\x1b[90m${s}\x1b[0m`,
  boldGreen: (s) => `\x1b[1;32m${s}\x1b[0m`,
  boldRed: (s) => `\x1b[1;31m${s}\x1b[0m`,
  boldBlue: (s) => `\x1b[1;34m${s}\x1b[0m`,
  boldYellow: (s) => `\x1b[1;33m${s}\x1b[0m`,
  boldCyan: (s) => `\x1b[1;36m${s}\x1b[0m`,
  boldPurple: (s) => `\x1b[1;35m${s}\x1b[0m`,
  boldGray: (s) => `\x1b[1;90m${s}\x1b[0m`,
};

export const print = {
  head: (s) => console.info(`${chalk.purple(s)}`),  
  boldHead : (s) => console.info(`${chalk.boldPurple(s)}`),
  section: (s) => console.info(`${chalk.yellow(s)}`),
  boldSection: (s) => console.info(`${chalk.boldYellow(s)}`),
  info: (s) => console.info(`${chalk.green(s)}`),
  boldInfo: (s) => console.info(`${chalk.boldGreen(s)}`),
  success: (s) => console.log(`${chalk.cyan(s)}`),
  boldSuccess: (s) => console.log(`${chalk.boldCyan(s)}`),
  gray: (s) => console.info(`${chalk.gray(s)}`),
  boldGray: (s) => console.info(`${chalk.boldGray(s)}`),
  blue: (s) => console.info(`${chalk.blue(s)}`),
  boldBlue: (s) => console.info(`${chalk.boldBlue(s)}`),
  error: (s) => console.error(`${chalk.red(s)}`),
  boldError: (s) => console.error(`${chalk.boldRed(s)}`),
  grayError: (s) => console.error(`${chalk.boldGray(s)}`),
  warn: (s) => console.warn(`${chalk.yellow(s)}`),
  boldWarn: (s) => console.warn(`${chalk.yellow(s)}`),
  debug: (s) => console.debug(`${chalk.gray(s)}`),
}
